### ISSUE TITLE
500 error with dual-control-plane demo

### ISSUE THREAD

**Issue by snavti** [GoogleCloudPlatform/istio-samples#23]
I encountered the 500 Error described in the readme, despite being able to access services from either mesh.

```
kubectl -n cluster1 exec -it currencyservice-668f49f985-vr4b5 -c istio-proxy /bin/sh
$ ping frontend.hipster2.global                   
PING frontend.hipster2.global (127.255.0.5) 56(84) bytes of data.
64 bytes from 127.255.0.5: icmp_seq=1 ttl=64 time=0.041 ms
64 bytes from 127.255.0.5: icmp_seq=2 ttl=64 time=0.048 ms
64 bytes from 127.255.0.5: icmp_seq=3 ttl=64 time=0.061 ms
```

```
kubectl -n cluster2 exec -it frontend-85d9fd86f8-j2t7h -c istio-proxy /bin/sh
$ ping currencyservice.hipster1.global
PING currencyservice.hipster1.global (127.255.0.4) 56(84) bytes of data.
64 bytes from 127.255.0.4: icmp_seq=1 ttl=64 time=0.023 ms
64 bytes from 127.255.0.4: icmp_seq=2 ttl=64 time=0.045 ms
64 bytes from 127.255.0.4: icmp_seq=3 ttl=64 time=0.051 ms
64 bytes from 127.255.0.4: icmp_seq=4 ttl=64 time=0.025 ms

```
There appears to be a networking issue associated with istio-egressgateway?

```
shiyghan@cs-6000-devshell-vm-ae6c0d48-5ff9-4513-a483-22a4c1fb4615:~$ istioctl proxy-status
NAME                                                   CDS                            LDS        EDS               RDS          PILOT                            VERSION
cartservice-57c6949b9-qxf9k.cluster2                   SYNCED                         SYNCED     SYNCED (50%)      SYNCED       istio-pilot-658f69f5dd-lnxnv     1.1.3
frontend-85d9fd86f8-mh7w4.cluster2                     SYNCED                         SYNCED     SYNCED (50%)      SYNCED       istio-pilot-658f69f5dd-lnxnv     1.1.3
istio-egressgateway-54bdd4f4bf-xdb8q.istio-system      STALE (Never Acknowledged)     SYNCED     SYNCED (100%)     NOT SENT     istio-pilot-658f69f5dd-lnxnv     1.1.3
istio-ingressgateway-589c9b9944-47fwj.istio-system     SYNCED                         SYNCED     SYNCED (100%)     SYNCED       istio-pilot-658f69f5dd-lnxnv     1.1.3
productcatalogservice-7b94dfb45c-2dmgp.cluster2        SYNCED                         SYNCED     SYNCED (50%)      SYNCED       istio-pilot-658f69f5dd-lnxnv     1.1.3
recommendationservice-656b857955-fthjd.cluster2        SYNCED                         SYNCED     SYNCED (50%)      SYNCED       istio-pilot-658f69f5dd-lnxnv     1.1.3
```

**Comment by askmeegs** [comment]
Hi, I just got this demo working with Istio v1.1.3 (frontend returns `200`, can access services outside its cluster). I also see a `STALE` status for `istio-egressgateway`, which makes me think that this isn't the issue in your environment causing the `500` error. 

Can you paste the output of this command for both clusters? 

```
kubectl get svc -n istio-system istio-ingressgateway
``` 

And then can you paste the contents of `./cluster1/serviceentries.yaml` and `./cluster2/serviceentries.yaml`? Thank you!

**Comment by snavti** [comment]
This is the Ingress gateway for Cluster 1

```
shiyghan@cs-6000-devshell-vm-2b6b4f8f-674f-4282-a7d9-66fc4b562c64:~$ kubectl config use-context gke_hipster-project-1_us-central1-a_hipster-cluster-1
Switched to context "gke_hipster-project-1_us-central1-a_hipster-cluster-1".
shiyghan@cs-6000-devshell-vm-2b6b4f8f-674f-4282-a7d9-66fc4b562c64:~$ kubectl get svc -n istio-system istio-ingressgateway
NAME                   TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                                                                                                                                      AGE
istio-ingressgateway   LoadBalancer   10.23.245.21   35.193.229.20   15020:30884/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:31976/TCP,15030:32688/TCP,15031:30217/TCP,15032:32420/TCP,15443:31254/TCP   1h
shiyghan@cs-6000-devshell-vm-2b6b4f8f-674f-4282-a7d9-66fc4b562c64:~$
```
This is the service-entries.yaml file for Cluster 1

```
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: adservice-entry
spec:
  hosts:
  - adservice.hipster1.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 9555
    protocol: GRPC
  resolution: DNS
  addresses:
  - 127.255.0.2
  endpoints:
  - address: 35.193.229.20
    ports:
      grpc: 15443
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: checkoutservice-entry
spec:
  hosts:
  - checkoutservice.hipster1.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 5050
    protocol: GRPC
  resolution: DNS
  addresses:
  - 127.255.0.3
  endpoints:
  - address: 35.193.229.20
    ports:
      grpc: 15443
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: currencyservice-entry
spec:
  hosts:
  - currencyservice.hipster1.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 7000
    protocol: GRPC
  resolution: DNS
  addresses:
  - 127.255.0.4
  endpoints:
  - address: 35.193.229.20
    ports:
      grpc: 15443
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: shippingservice-entry
spec:
  hosts:
  - shippingservice.hipster1.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 50051
    protocol: GRPC
  resolution: DNS
  addresses:
  - 127.255.0.8
  endpoints:
  - address: 35.193.229.20
    ports:
      grpc: 15443
```

This is the Ingress for Cluster 2

```
shiyghan@cs-6000-devshell-vm-2b6b4f8f-674f-4282-a7d9-66fc4b562c64:~$ kubectl config use-context gke_hipster-project-2_us-east4-a_hipster-cluster-2
Switched to context "gke_hipster-project-2_us-east4-a_hipster-cluster-2".
shiyghan@cs-6000-devshell-vm-2b6b4f8f-674f-4282-a7d9-66fc4b562c64:~$ kubectl get svc -n istio-system istio-ingressgateway
NAME                   TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)                                                                                                                                      AGE
istio-ingressgateway   LoadBalancer   10.51.246.131   35.245.226.53   15020:30552/TCP,80:31380/TCP,443:31390/TCP,31400:31400/TCP,15029:30331/TCP,15030:31364/TCP,15031:30496/TCP,15032:32013/TCP,15443:30783/TCP   1h
shiyghan@cs-6000-devshell-vm-2b6b4f8f-674f-4282-a7d9-66fc4b562c64:~$
```

This is the service-entries.yaml file for Cluster 2

```
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: frontendservice-entry
spec:
  hosts:
  - frontend.hipster2.global
  location: MESH_INTERNAL
  ports:
  - name: http1
    number: 80
    protocol: http
  resolution: DNS
  addresses:
  - 127.255.0.5
  endpoints:
  - address: 35.245.226.53
    ports:
      http1: 15443
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: productcatalogservice-entry
spec:
  hosts:
  - productcatalogservice.hipster2.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 3550
    protocol: GRPC
  resolution: DNS
  addresses:
  - 127.255.0.6
  endpoints:
  - address: 35.245.226.53
    ports:
      grpc: 15443
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: cartservice-entry
spec:
  hosts:
  - cartservice.hipster2.global
  location: MESH_INTERNAL
  ports:
  - name: grpc
    number: 7070
    protocol: GRPC
  resolution: DNS
  addresses:
  - 127.255.0.7
  endpoints:
  - address: 35.245.226.53
    ports:
      grpc: 15443
```
